In [1]:
from high_dim_utils import *

In [2]:
d = 10
y_noise_scale = 0.1
test_msc = [np.zeros(d), 1, 0]

### Prepare pre-trained model

In [3]:
# a pretrained model
np.random.seed(324)
sample_size = 1000
Xtr = np.random.uniform(-3, 3, d*sample_size).reshape(sample_size, d)
Ytr = generate_response(Xtr, 0.1)

kernel = GPy.kern.RBF(input_dim=d)
model = GPy.models.GPRegression(Xtr, Ytr.reshape(-1,1), kernel)

# optimize the model parameters
model.optimize()
f = model.predict

### Compute the magnitude of the error

In [4]:
np.mean(np.abs(f(Xtr)[0] - Ytr))

1.0073249887366835

### Replications

In [5]:
K_int = [2, 10]
topK = 3
ab_threshold = 0.01

n_int = [50, 100]
mean_int = [-1,1]
std_int = [0.8, 1]
cor_int = [0, 0.2]
alpha = 0.1

R = 200
num_method = 4

In [6]:
covs, lens, counts, working_groups_mat = replications(R, d, f, K_int, topK,  ab_threshold,
                       n_int, mean_int, std_int, cor_int, y_noise_scale, test_msc,0.1 )

# WCP then merged
print('Marginal coverage:')
print(np.round(np.mean(covs, axis = 0), decimals = 3))
print('')

print('Probabiilty of getting finite prediction intervals')
print(np.round(np.mean(counts, axis = 0), decimals = 3))
print('')

print('Informative coverage probability:')
print( np.round( np.sum(counts*covs, axis = 0) /np.sum(counts, axis = 0), decimals = 3)  )
print('')

avg_finite_len = []
for k in range(num_method):
    lenk = lens[:,k]
    lenk = lenk[~np.isinf(lenk)]
    if len(lenk) == 0:
        avg_finite_len.append(  np.inf )
    else:
        avg_finite_len.append( np.round( np.mean(lenk), decimals=3) )
print('Lengths of informative intervals:')
print(avg_finite_len )
print('')


print('Working groups number:')
print(np.round( np.quantile(working_groups_mat,0.5, axis = 0) ,decimals = 3))

0
50
100
150
Marginal coverage:
[0.86  0.93  0.97  0.905]

Probabiilty of getting finite prediction intervals
[0.985 0.915 0.845 0.995]

Informative coverage probability:
[0.858 0.923 0.964 0.905]

Lengths of informative intervals:
[0.349, 0.418, 0.505, 0.395]

Working groups number:
[6. 1. 3. 6.]


In [9]:
cor_int = [0.7, 0.9]

In [10]:
covs, lens, counts, working_groups_mat = replications(R, d, f, K_int, topK,  ab_threshold,
                       n_int, mean_int, std_int, cor_int, y_noise_scale, test_msc,0.1 )

# WCP then merged
print('Marginal coverage:')
print(np.round(np.mean(covs, axis = 0), decimals = 3))
print('')

print('Probabiilty of getting finite prediction intervals')
print(np.round(np.mean(counts, axis = 0), decimals = 3))
print('')

print('Informative coverage probability:')
print( np.round( np.sum(counts*covs, axis = 0) /np.sum(counts, axis = 0), decimals = 3)  )
print('')

avg_finite_len = []
for k in range(num_method):
    lenk = lens[:,k]
    lenk = lenk[~np.isinf(lenk)]
    if len(lenk) == 0:
        avg_finite_len.append(  np.inf )
    else:
        avg_finite_len.append( np.round( np.mean(lenk), decimals=3) )
print('Lengths of informative intervals:')
print(avg_finite_len )
print('')


print('Working groups number:')
print(np.round( np.quantile(working_groups_mat,0.5, axis = 0) ,decimals = 3))

0
50
100
150
Marginal coverage:
[0.95  0.96  0.965 0.915]

Probabiilty of getting finite prediction intervals
[0.74  0.4   0.4   0.905]

Informative coverage probability:
[0.932 0.9   0.912 0.906]

Lengths of informative intervals:
[0.454, 0.472, 0.472, 0.416]

Working groups number:
[5. 1. 1. 5.]
