In [1]:
from mg_1d_utils import *

In [2]:
y_noise_scale = 0.1
test_mv = [0, 3]

### Prepare pre-trained model

In [3]:
# a pretrained model
np.random.seed(324)
low, high, sample_size = -20, 20, 100
Xtr = np.random.uniform(low, high, sample_size)
Ytr = generate_response(Xtr, 0.1)

kernel = GPy.kern.RBF(input_dim=1)
model = GPy.models.GPRegression(Xtr.reshape(-1,1), Ytr.reshape(-1,1), kernel)

# optimize the model parameters
model.optimize()
f = model.predict

### Replications

In [4]:
R = 5000
num_method = 4
mean_int = [-6, 6]
n_int = [10, 101]

In [5]:
topK = 3
ab_threshold = 0.01


# small number of groups + small variance
K_int = [3, 11]
std_int = [0.5, 1.5]

In [6]:
covs, lens, counts, working_groups_mat = replications(R, f, K_int, topK,  ab_threshold,
                       n_int, mean_int, std_int, y_noise_scale, test_mv, w, w_pool, 0.1 )
# WCP then merged

print('Marginal coverage:')
print(np.round(np.mean(covs, axis = 0), decimals = 3))
print('')

print('Probabiilty of getting finite prediction intervals')
print(np.round(np.mean(counts, axis = 0), decimals = 3))
print('')

print('Informative coverage probability:')
print( np.round( np.sum(counts*covs, axis = 0) /np.sum(counts, axis = 0), decimals = 3)  )
print('')

avg_finite_len = []
for k in range(num_method):
    lenk = lens[:,k]
    lenk = lenk[~np.isinf(lenk)]
    if len(lenk) == 0:
        avg_finite_len.append(  np.inf )
    else:
        avg_finite_len.append( np.round( np.mean(lenk), decimals=3) )
print('Lengths of informative intervals:')
print(avg_finite_len )
print('')


print('Working groups number:')
print(np.round( np.quantile(working_groups_mat,0.5, axis = 0) ,decimals = 3))

Marginal coverage:
[0.846 0.932 0.963 0.915]

Probabiilty of getting finite prediction intervals
[0.889 0.584 0.747 0.916]

Informative coverage probability:
[0.827 0.884 0.95  0.907]

Lengths of informative intervals:
[0.311, 0.37, 0.445, 0.361]

Working groups number:
[6. 1. 3. 6.]


In [7]:
topK = 3
ab_threshold = 0.01
# small number of groups + small variance
K_int = [3, 11]
std_int = [1.5, 2.5]

In [8]:
covs, lens, counts, working_groups_mat = replications(R, f, K_int, topK,  ab_threshold,
                                                         n_int, mean_int, 
                                                      std_int,  y_noise_scale, test_mv,
                                                      w, w_pool, 0.1 )
# WCP then merged

print('Marginal coverage:')
print(np.round(np.mean(covs, axis = 0), decimals = 3))
print('')

print('Probabiilty of getting finite prediction intervals')
print(np.round(np.mean(counts, axis = 0), decimals = 3))
print('')

print('Informative coverage probability:')
print( np.round( np.sum(counts*covs, axis = 0) /np.sum(counts, axis = 0), decimals = 3)  )
print('')

avg_finite_len = []
for k in range(num_method):
    lenk = lens[:,k]
    lenk = lenk[~np.isinf(lenk)]
    if len(lenk) == 0:
        avg_finite_len.append(  np.inf )
    else:
        avg_finite_len.append( np.round( np.mean(lenk), decimals=3) )
print('Lengths of informative intervals:')
print(avg_finite_len )
print('')


print('Working groups number:')
print(np.round( np.quantile(working_groups_mat,0.5, axis = 0) ,decimals = 3))

Marginal coverage:
[0.808 0.917 0.945 0.902]

Probabiilty of getting finite prediction intervals
[0.984 0.881 0.949 0.99 ]

Informative coverage probability:
[0.805 0.905 0.942 0.901]

Lengths of informative intervals:
[0.294, 0.376, 0.432, 0.359]

Working groups number:
[7. 1. 2. 7.]
